server:
  port: 8085

#Nacos启动服务发现
spring:
  cloud:
    nacos:
      discovery:
        #Nacos server的配置地址
        server-addr: 127.0.0.1:8848
  #服务提供者的名称
  application:
    name: service-map

amap:
  key: 9e0a1d62cd4b196f8cd73a81a3899bc1