server:
  port: 8081

#Nacos启动服务发现
spring:
  cloud:
    nacos:
      discovery:
        #Nacos server的配置地址
        server-addr: 127.0.0.1:8848
  #服务提供者的名称
  application:
    name: api-passenger

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0